# Generated by Django 5.2.11 on 2026-03-28 08:11

import django.db.models.deletion
import turbodrf.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompiledArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compiled_articles', to='test_app.relatedmodel')),
                ('categories', models.ManyToManyField(blank=True, related_name='compiled_articles', to='test_app.category')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(turbodrf.mixins.TurboDRFMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompiledSampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiled_samples', to='test_app.relatedmodel')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(turbodrf.mixins.TurboDRFMixin, models.Model),
        ),
    ]
