name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
        pip install -e ".[dev]"
    
    - name: Run black
      run: black --check turbodrf/ tests/
    
    - name: Run isort
      run: isort --check-only turbodrf/ tests/
    
    - name: Run flake8
      run: flake8 turbodrf/ tests/