name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/pyproject.toml', '**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy bandit safety
        pip install -e ".[dev]"
    
    - name: Format check with black
      run: |
        black --check --diff turbodrf/ tests/
    
    - name: Import sort check with isort
      run: |
        isort --check-only --diff turbodrf/ tests/
    
    - name: Lint with flake8
      run: |
        flake8 turbodrf/ tests/
    
    - name: Type check with mypy
      run: |
        mypy turbodrf/ --ignore-missing-imports --follow-imports=skip || true
    
    - name: Security check with bandit
      run: |
        bandit -r turbodrf/ -ll || true
    
    - name: Check dependencies with safety
      run: |
        safety check --json || true

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint radon xenon
        pip install -e ".[dev]"
    
    - name: Run pylint
      run: |
        pylint turbodrf/ --exit-zero --output-format=colorized
    
    - name: Check cyclomatic complexity
      run: |
        radon cc turbodrf/ -a -nb
    
    - name: Check maintainability index
      run: |
        radon mi turbodrf/ -nb
    
    - name: Check code complexity with xenon
      run: |
        xenon --max-absolute B --max-modules B --max-average A turbodrf/ || true

  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    
    - name: Run pre-commit
      run: |
        pre-commit run --all-files || true